### ISSUE TITLE
templates available from within Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/silex-templates#2]
The main website, which lists all the available templates, should be loaded in Silex when the user chooses "new from template". And also at startup, Silex should open this dialog instead of a blank page (add the blank page "creation template" as a template?).

Also, the list of templates and each template should have a link to "edit in Silex". Silex should open the template given in get params.
##

**Comment by singchan** [comment]
done 
https://github.com/silexlabs/Silex/issues/283
