### ISSUE TITLE
Link to templatamatic for the paid templates.

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/silex-templates#22]
https://www.templamatic.com/templates/silex
##

**Comment by lexoyo** [comment]
yes this is encourage to make both free and paid templates so that the ecosystem grows... You think this is a bad idea?

**Comment by pierreozoux** [comment]
Was just saying it wold be nice to make a link here to the paid templates.

**Comment by lexoyo** [comment]
Oh ok :)
Good idea !

**Comment by lexoyo** [comment]
Templamatic is definitely down and we have no more paid templates... I'll close this issue
