### ISSUE TITLE
templates cleanup: which templates should we remove? 

### ISSUE THREAD

**Issue by singchan** [silexlabs/silex-templates#26]
Which templates do you think are not useful and we should remove?
http://templates.silex.me/

**Comment by JbIPS** [comment]
I know world_of_workcraft is the best template, but it have to go :smile:

**Comment by ceubri** [comment]
Templates not useful : 
- http://silex-templates.silex.me/minimal-grey
- http://silex-templates.silex.me/sublime_cv/index.html

**Comment by budislav** [comment]
http://silex-templates.silex.me/perso1/index.html
http://silex-templates.silex.me/fictional-studio/index.html

**Comment by lexoyo** [comment]
thank you guys!

**Comment by lexoyo** [comment]
Done! I did remove the template and added a new one and fixed everything
Help me test each template!
http://preprod.silex.me/
