### ISSUE TITLE
Templamatic disappeared?

### ISSUE THREAD

**Issue by ghost** [silexlabs/silex-templates#52]
Looks like Templamatic.com has been taken offline, and the domain is [about to expire](https://whois.domaintools.com/templamatic.com). Your repo seems to rely quite a bit on that site for paid templates, thought you'd like to know.

**Comment by lexoyo** [comment]
Thank you @haverholm

**Comment by lexoyo** [comment]
Templamatic is definitely down and we have no more paid templates... I'll close this issue
