### ISSUE TITLE
Images bug/issue

### ISSUE THREAD

**Issue by exadeci** [silexlabs/silex-templates#7]
I copied https://github.com/silexlabs/silex-templates/tree/gh-pages/templates/minimal-grey
folder on my dropbox
Opened the editable.html with silex
Preview in View > Preview looks perfect
But after publishing it looks like this:
![ggg](https://cloud.githubusercontent.com/assets/1394130/3553824/9dd20f80-0907-11e4-8abc-15d040c26d99.PNG)

The only image that gets moved is the triangle.gif

**Comment by lexoyo** [comment]
Hello @exadeci 
Just to let you know that I am investigating. I reproduced the bug and it comes from Silex itself, not the template. You can work on the template, it will publish well after I made the fix on www.silex.me
Thx

**Comment by exadeci** [comment]
Okay thank you

**Comment by lexoyo** [comment]
should be fixed with this new release (it is online right now)
https://github.com/silexlabs/Silex/pull/366
